### ISSUE TITLE
gradlew build失败

### ISSUE THREAD

**Issue by moz1q1** [MegatronKing/StringFog#14]
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ByteVector.putUTF8(Unknown Source)
        at org.objectweb.asm.ClassWriter.newUTF8(Unknown Source)
        at org.objectweb.asm.ClassWriter.b(Unknown Source)
        at org.objectweb.asm.ClassWriter.a(Unknown Source)
        at org.objectweb.asm.MethodWriter.visitLdcInsn(Unknown Source)
        at org.objectweb.asm.MethodVisitor.visitLdcInsn(Unknown Source)
        at com.github.megatronking.stringfog.plugin.StringFogClassVisitor$1.visitLdcInsn(StringFogClassVisitor.java:131)
        at org.objectweb.asm.ClassReader.a(Unknown Source)
        at org.objectweb.asm.ClassReader.b(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.github.megatronking.stringfog.plugin.StringFogClassInjector.processClass(StringFogClassInjector.java:112)
        at com.github.megatronking.stringfog.plugin.StringFogClassInjector.doFog2Class(StringFogClassInjector.java:52)
        at com.github.megatronking.stringfog.plugin.StringFogClassInjector$doFog2Class.call(Unknown Source)
        at com.github.megatronking.stringfog.plugin.StringFogTransform$_transform_closure5$_closure12.doCall(StringFogTransform.groovy:167)
        at com.github.megatronking.stringfog.plugin.StringFogTransform$_transform_closure5.doCall(StringFogTransform.groovy:161)
        at com.github.megatronking.stringfog.plugin.StringFogTransform.transform(StringFogTransform.groovy:125)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more

**Comment by moz1q1** [comment]
java.lang.IllegalArgumentException (no error message)

**Comment by moz1q1** [comment]
忘记过滤混淆，文档最好补出来嘛

**Comment by MegatronKing** [comment]
看样子是某个字符串加密后长度超过65535了，详见ByteVector：
```
    public ByteVector putUTF8(final String s) {
        int charLength = s.length();
        if (charLength > 65535) {
            throw new IllegalArgumentException();
        }
        ...
    }
```
安装Base64算法，原字符串长度不应该超过65535*0.75

**Comment by moz1q1** [comment]
@MegatronKing 可能是吧，可是我换了另外一个工程编译，看了下，还行不能指定我的jar吧，感觉没效果，我是想加密我指定的jar，我在gradle构建自己的sdk

**Comment by MegatronKing** [comment]
可以用fogPackages配置指定的包加密

**Comment by moz1q1** [comment]
@MegatronKing 我不是想指定包名，我想指定路径，可以吗，我打好的jar

**Comment by MegatronKing** [comment]
这个目前做不到，加密步骤是在编译成字节码之后进行的，这个时候所有字节码都是放在build目录下面，已经没法知道jar的原始路径了

**Comment by moz1q1** [comment]
因为我也用gradle命令把class文件打成一个jar包
先是执行build->合成jar->dex，但是我发现用你这库的时候，build生成的class文件没有你的库代码

**Comment by moz1q1** [comment]
@MegatronKing

**Comment by moz1q1** [comment]
task xxxx(type: Jar, dependsOn: ['build']) {
        appendix = ""
        baseName = "xxx"
        version = ""
        classifier = ""
        //后缀名
        extension = "jar"
        //jar包输出路径
        destinationDir = file('build/jar') //
        //需打包的资源所在的路径集
        def srcClassDir = ["build/intermediates/classes/release"];
        //初始化资源路径集
        from srcClassDir
        //添加依赖的jar文件，zipTree为了解压文件
        from(project.zipTree("libs/test_sdk.jar"))
        //from(project.zipTree("libs/Android_Map3D_SDK_V6.1.0_20180330.jar"))
        //去除路径集下部分的资源，合并其他的包，可能依赖R文件，因此要明确点这里
        exclude "com/android/google/**/BuildConfig.class"
        exclude "com/android/google/**/R.class"
        exclude "com/android/google/**/R\$*.class"
        //只导入资源路径集下的部分资源，这句话，导致其他包，没办法引入进来，所以要注释
        //include "com/android/google/code/**/*.class"
    }

**Comment by moz1q1** [comment]
我不知道你有没有编译jar

**Comment by MegatronKing** [comment]
StringFog的原理同混淆类似，都是在transform里面做处理，能看到transformClassesWithStringFogForXXX的task。所以理论上不会影响你那边的task

**Comment by moz1q1** [comment]
你可能还没明白，我说构建 build的时候没有你jar的class代码生成出来呀

**Comment by moz1q1** [comment]
@MegatronKing

**Comment by moz1q1** [comment]
你可以试试gradlew build 看看

**Comment by MegatronKing** [comment]
哪个没有生产出来呢，StringFog.class这个？

**Comment by moz1q1** [comment]
涉及到你这库的那几个类都没有 @MegatronKing

**Comment by MegatronKing** [comment]
compile 'com.github.megatronking.stringfog:lib:1.2.2' 这个也没有？ 这是正常的库依赖，不可能没有的，如果没有我只能是怀疑你gradle出问题了。

**Comment by moz1q1** [comment]
这个有呀，不知道为何build后没加上来，其他包是正常的 @MegatronKing

**Comment by moz1q1** [comment]
方便的话，加下qq：709847739 我问下你

**Comment by MegatronKing** [comment]
Fixed in 2.0.0
