### ISSUE TITLE
java11 编译通不过

### ISSUE THREAD

**Issue by ucxl** [MegatronKing/StringFog#59]
感谢抽空看看，谢谢

**Comment by MegatronKing** [comment]
可以试试3.0.0版本，升级了ASM。

**Comment by ucxl** [comment]
辛苦了

**Comment by ucxl** [comment]
这里改成11还是无法编译，改成1.8就可以，在java11的状态下注释/*    id 'stringfog'*/ 也可以编译通过

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }


    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.NullPointerException
	at com.github.megatronking.stringfog.plugin.StringFogMappingPrinter.output(StringFogMappingPrinter.java:68)
	at com.github.megatronking.stringfog.plugin.StringFogClassVisitor$StubMethodVisitor.insertDecryptInstructions(StringFogClassVisitor.java:272)
	at com.github.megatronking.stringfog.plugin.StringFogClassVisitor$3.visitLdcInsn(StringFogClassVisitor.java:209)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2421)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:744)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at com.github.megatronking.stringfog.plugin.StringFogClassInjector.processClass(StringFogClassInjector.java:120)
	at com.github.megatronking.stringfog.plugin.StringFogClassInjector.doFog2Class(StringFogClassInjector.java:64)
	at com.github.megatronking.stringfog.plugin.StringFogClassInjector$doFog2Class.call(Unknown Source)
	at com.github.megatronking.stringfog.plugin.StringFogTransform$_transform_closure4$_closure10.doCall(StringFogTransform.groovy:185)
	at jdk.internal.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.github.megatronking.stringfog.plugin.StringFogTransform$_transform_closure4.doCall(StringFogTransform.groovy:181)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.github.megatronking.stringfog.plugin.StringFogTransform.transform(StringFogTransform.groovy:149)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:284)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:69)
	... 126 more

**Comment by MegatronKing** [comment]
如果没问题，ISSUE我先关了。
